AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

plugins:
  rubocop-minitest


Minitest/MultipleAssertions:
  Enabled: false
